import {
    paperpresentation,
    projecpresentation,
    webmaster,
    crashcode,
    game,
    googlehunt
} from "../../../assets/index.js";

const TechCardContent = [{
        id: 1,
        img: paperpresentation,
        coordinator: " Dr.Sangeetha HoD/AI & DS",
        studentCoordinator: "Mr. Samson Durai 3rd IT",
        email: "infest2k25cse@gmail.com",
        stdmobile: "9629110972",
        mobile: "8015169004",
        eventTitle: "Paper Presentation",
        eventDesc: "A paper presentation is a formal way of sharing research findings, innovative ideas, or case studies with an audience in academic, professional, or technical settings. It involves presenting a well-researched paper through a structured oral talk, often supported by slides or visual aids. The goal is to communicate key insights effectively, engage the audience, and encourage discussions. ",
        rules: [
            "Maximum 4 members per team.",
            "The paper topics can be chosen by your own.",
            "Abstract should be sent 1 week before (infest2kcse@gmail.com).",
            "Abstract should not exceed more than 250 words and Paper should not exceed 15 pages.",
            "Abstract should be in the given format :",
            "Title- theme of the paper.",
            "Names of the students and their E-mail ID’S.",
            "Name of the Institute & City.",
            "Each team is allocated a total presentation time of 3 – 5 minutes.",
            "Submissions must be in the form of a POWER POINT PRESENTATION.",
            "Students should submit the PPT before 2 days via mail(infest2k25cse@gmail.com).",
        ],
        criteria: [
            "Clarity.",
            "Delivery (Confidence, Body Language, Dynamism & Vocal delivery)",
        ]
    },
    {
        id: 2,
        img: projecpresentation,
        coordinator: "Dr.Loganathan HoD/IT",
        studentCoordinator: "Mr.Ajay 3rd IT",
        email: "infest2k25cse@gmail.com",
        stdmobile: "9789413779",
        mobile: "9942973200",
        eventTitle: "Project Presentation",
        eventDesc: "A project presentation is a structured way of showcasing a project’s objectives, progress, outcomes, and impact to an audience. It is commonly used in academic, business, and technical settings to communicate ideas, problem-solving approaches, and innovations. The presentation typically includes visual aids, such as slides, charts, and prototypes, to enhance understanding and engagement.",
        rules: [
            "Abstract should be sent 2 days before the event",
            "Maximum 4 members per team .",
            "The Project topics shall be choosen by their own.",
            "Abstract should not exceed more than 250 words and paper should not exceed 15 slides.",
            "A team should present the project upto 8 minutes.",
        ],
        criteria: [
            "Delivery (Communication skills, confidence, and Proper delivery of content )",
            "Visuals (Quality of content and effectiveness of slides, use of multimedia, Attractive slides)",
        ],
    },
    {
        id: 3,
        img: googlehunt,
        coordinator: "A.Saranya AP/CSE",
        studentCoordinator: "Ms. Sri Dharshana 3rd CSE",
        email: "infest2k25cse@gmail.com",
        stdmobile: "9003698188",
        mobile: "9786655443",
        eventTitle: "Google Hunt",
        eventDesc: '"Google Hunt" is a fast-paced competition with two rounds: "Google Search Challenge" and "Google Feats." It is all about being fast and precise with Google search skills',
        rules: [
            "No. of Rounds : 2",
            "Round 1 is Google Search Challenge and Duration of 25 Minutes.",
            "Round 2 is Google Feats and Duration of 30 Minutes.",
            "Round 1 :",
            "As per the participants, teams are separated.",
            "For each team, commonly 15 questions are given and 40sec is given to answer the question.",
            "The teams that gained more points will move to the next round.",
            "Round 2 :",
            "In this round the time alone will be reduced for 1 min to search for the question and answer it.",
            "Other than that, you can follow the rules used for round 1.",
            "General Rules :",
            "Mobile phones are allowed for searching answers.",
            "You must only use google to search for the question.",
            "Using ChatGPT and other Gen AI tools are prohibited",
        ],
        criteria: [
            "Accuracy, Speed, Teamwork, Problem Solving Skills",
        ]
    },
    {
        id: 4,
        img: crashcode,
        coordinator: "P.Sundari AP/IT",
        studentCoordinator: "Mr. Hameshwar 3rd IT",
        email: "infest2k25cse@gmail.com",
        stdmobile: "8072714569",
        mobile: "9095125476",
        eventTitle: "Crash Your Code",
        eventDesc: "Crash Your Code is an exciting coding challenge or debugging competition where participants intentionally test, break, or improve their code by identifying vulnerabilities, errors, or inefficiencies. It is designed to enhance problem-solving skills, debugging expertise, and coding efficiency in a fun and competitive environment.     ",
        rules: [
            "No. of Rounds : 2",
            "Round 1 is MCQ and Round 2 is Debugging and Problem Solving.",
            "Round 1 Duration is 20 Mins and Round 2 Duration is 30 Mins.",
            "Any Programming language is allowed to solve the problems.",
            "All rounds will be conducted in Hackerrank, etc.",
            "Mobile Phone is not allowed.",
            "Switching tabs are stricly prohibited.",
            "Plagarism is prohibited.",
        ],
        criteria: [
            "Problem Solving Skills.",
            "Coding Proficiency.",
            "Innovation and Optimization.",
            "Adaptability and Resilence."
        ]
    },
    {
        id: 5,
        img: webmaster,
        coordinator: "R.Saranya Lec/CSE",
        studentCoordinator: "Ms.Elavarasi 3rd CSE",
        email: "infest2k25cse@gmail.com",
        mobile: "9003650974",
        stdmobile: "8220679393",
        eventTitle: "Web Master",
        eventDesc: "Web Master is an event where the participants have to express their web development skills by creating a website with given requirements.",
        rules: [
            "There will be two rounds :",
            "Round 1: MCQ (Shortlisted participants will be participated in round 2)",
            "Round 2: web page development ",
            "Individual Participants only.",
            "Switching tabs is prohibited.",
            "Using of Chatgpt and other Gen 4.AI tools are prohibited.",
            "Mobile phones are prohibited.",
            "Required assests for web page will be provided.",
        ],
        criteria: [
            "Creativity",
            "Content Quality",
            "Colourful look",
            "Attractive design",
            "Interactivity",
        ]
    },
    {
        id: 6,
        img: game,
        coordinator: "M.Raja AP/IT",
        studentCoordinator: "Mr. Rohith 3rd CSE",
        email: "infest2k25cse@gmail.com",
        stdmobile: "9626490046",
        mobile: "9994160955",
        eventTitle: "Gaming",
        eventDesc: "Join us for an exhilarating day where gamers of all levels come together to celebrate their passion for gaming! Test your skills in popular games such as Valorant, Freefire, and PUBG. Prizes await the top players!",
        rules: [
            "No. of Rounds : 2",
            "Round 1 is MCQ and Round 2 is Debugging and Problem Solving.",
            "Round 1 Duration is 20 Mins and Round 2 Duration is 30 Mins.",
            "Any Programming language is allowed to solve the problems.",
            "All rounds will be conducted in Hackerrank, etc.",
            "Mobile Phone is not allowed.",
            "Switching tabs are stricly prohibited.",
            "Plagarism is prohibited.",
        ],
        criteria: [
            "Problem Solving Skills.",
            "Coding Proficiency.",
            "Innovation and Optimization.",
            "Adaptability and Resilence."
        ]
    },
];
export default TechCardContent;