import {
    paperpresentation,
    projecpresentation,
    webmaster,
    crashcode,
    game,
    googlehunt,
    model,
    poster,
} from "../../../assets/index.js";

const TechCardContent = [{
    id: 1,
    img: paperpresentation,
    coordinator: " Dr. G. Selvavinayagam HoD/CSE,Dr.Sangeetha HoD/AI & DS,Mr. K. Madeshwaran AP/IT",
    studentCoordinator: "Mr. Ajayan 3rd AI&DS, Ms. Harshini 3rd CSE ,Ms.Arputhavali 3rd IT",
    email: "infest2k26cse@gmail.com",
    stdmobile: "9629303987",
    mobile: "9865222182",
    eventTitle: "Paper Presentation",
    eventDesc: "A paper presentation is a formal way of sharing research findings, innovative ideas, or case studies with an audience in academic, professional, or technical settings. It involves presenting a well-researched paper through a structured oral talk, often supported by slides or visual aids. The goal is to communicate key insights effectively, engage the audience, and encourage discussions. ",
    rules: [
        "Maximum 4 members per team.",
        "The paper topics can be chosen by your own.",
        "Abstract should be sent 1 week before (infest2kcse@gmail.com).",
        "Abstract should not exceed more than 250 words and Paper should not exceed 15 pages.",
        "Abstract should be in the given format :",
        "Title- theme of the paper.",
        "Names of the students and their E-mail ID’S.",
        "Name of the Institute & City.",
        "Each team is allocated a total presentation time of 3 – 5 minutes.",
        "Submissions must be in the form of a POWER POINT PRESENTATION.",
        "Students should submit the PPT before 2 days via mail(infest2k25cse@gmail.com).",
    ],
    criteria: [
        "Clarity.",
        "Delivery (Confidence, Body Language, Dynamism & Vocal delivery)",
    ]
},
{
    id: 2,
    img: projecpresentation,
    coordinator: "Mr. M. Nagarajan AP/CSE, Mr. Arockia Selvaraj HoD/IT,Mrs. P. Gokila HoD/CSE",
    studentCoordinator: "Ms. V. Srivarshini 3rd CSE,Mr. J. Josuva 3rd AI&DS,Ms. Arunika 3rd IT",
    email: "infest2k26cse@gmail.com",
    stdmobile: "7200720362",
    mobile: "7708103693",
    eventTitle: "Project Presentation",
    eventDesc: "A project presentation is a structured way of showcasing a project’s objectives, progress, outcomes, and impact to an audience. It is commonly used in academic, business, and technical settings to communicate ideas, problem-solving approaches, and innovations. The presentation typically includes visual aids, such as slides, charts, and prototypes, to enhance understanding and engagement.",
    rules: [
        "Abstract should be sent 2 days before the event",
        "Maximum 4 members per team .",
        "The Project topics shall be choosen by their own.",
        "Abstract should not exceed more than 250 words and paper should not exceed 15 slides.",
        "A team should present the project upto 8 minutes.",
    ],
    criteria: [
        "Delivery (Communication skills, confidence, and Proper delivery of content )",
        "Visuals (Quality of content and effectiveness of slides, use of multimedia, Attractive slides)",
    ],
},
{
    id: 3,
    img: googlehunt,
    coordinator: "A.Saranya AP/CSE, Mrs.R.S.Gayathri AP/AI & DS,Mr. K.Hema AP/IT",
    studentCoordinator: "Mr. Kathirvelan 3rd CSE,Ms. E. Deepika  3rd AI&DS,Ms. G. Jayasathika 3rd IT",
    email: "infest2k26cse@gmail.com",
    stdmobile: "8220320717",
    mobile: "8122299834",
    eventTitle: "Google Hunt",
    eventDesc: '"Google Hunt" is a fast-paced competition with two rounds: "Google Search Challenge" and "Google Feats." It is all about being fast and precise with Google search skills',
    rules: [
        "No. of Rounds : 2",
        "Round 1 is Google Search Challenge and Duration of 25 Minutes.",
        "Round 2 is Google Feats and Duration of 30 Minutes.",
        "Round 1 :",
        "As per the participants, teams are separated.",
        "For each team, commonly 15 questions are given and 40sec is given to answer the question.",
        "The teams that gained more points will move to the next round.",
        "Round 2 :",
        "In this round the time alone will be reduced for 1 min to search for the question and answer it.",
        "Other than that, you can follow the rules used for round 1.",
        "General Rules :",
        "Mobile phones are allowed for searching answers.",
        "You must only use google to search for the question.",
        "Using ChatGPT and other Gen AI tools are prohibited",
    ],
    criteria: [
        "Accuracy, Speed, Teamwork, Problem Solving Skills",
    ]
},
{
    id: 4,
    img: crashcode,
    coordinator: "P.Sundari AP/IT, Ms. S. Swarna AP/CSE,Ms. K. Mahalakshmi AP/CSE",
    studentCoordinator: "Mr. S. Thamu 3rd CSE, Ms. V. Natchathira Mala  3rd IT, Mr. C. Bala Murugan  3rd CSE",
    email: "infest2k26cse@gmail.com",
    stdmobile: "9342770217",
    mobile: "9095125476",
    eventTitle: "Crash Your Code",
    eventDesc: "Crash Your Code is an exciting coding challenge or debugging competition where participants intentionally test, break, or improve their code by identifying vulnerabilities, errors, or inefficiencies. It is designed to enhance problem-solving skills, debugging expertise, and coding efficiency in a fun and competitive environment.     ",
    rules: [
        "No. of Rounds : 2",
        "Round 1 is MCQ and Round 2 is Debugging and Problem Solving.",
        "Round 1 Duration is 20 Mins and Round 2 Duration is 30 Mins.",
        "Any Programming language is allowed to solve the problems.",
        "All rounds will be conducted in Hackerrank, etc.",
        "Mobile Phone is not allowed.",
        "Switching tabs are stricly prohibited.",
        "Plagarism is prohibited.",
    ],
    criteria: [
        "Problem Solving Skills.",
        "Coding Proficiency.",
        "Innovation and Optimization.",
        "Adaptability and Resilence."
    ]
},
{
    id: 5,
    img: webmaster,
    coordinator: "Mrs. R.Saranya AP/CSE, Ms. J. Jreeja AP/IT",
    studentCoordinator: "Ms. P. Lithika Sree 3rd AI&DS,Mr. Nithish  3rd CSE,Mr. G. Gokulanath 3rd IT",
    email: "infest2k26cse@gmail.com",
    mobile: "9003650974",
    stdmobile: "9344843005",
    eventTitle: "Web Master",
    eventDesc: "Web Master is an event where the participants have to express their web development skills by creating a website with given requirements.",
    rules: [
        "There will be two rounds :",
        "Round 1: MCQ (Shortlisted participants will be participated in round 2)",
        "Round 2: web page development ",
        "Individual Participants only.",
        "Switching tabs is prohibited.",
        "Using of Chatgpt and other Gen 4.AI tools are prohibited.",
        "Mobile phones are prohibited.",
        "Required assests for web page will be provided.",
    ],
    criteria: [
        "Creativity",
        "Content Quality",
        "Colourful look",
        "Attractive design",
        "Interactivity",
    ]
},
{
    id: 6,
    img: game,
    coordinator: "Mr. M.Raja AP/IT, Mr. Mohankumar AP/CSE",
    studentCoordinator: "Mr. Ramesh M 3rd CSE, Mr. Harishragvendraa 3rd AI&DS, Mr. Manoj 3rd IT",
    email: "infest2k26cse@gmail.com",
    stdmobile: "9360249539",
    mobile: "9994160955",
    eventTitle: "Gaming",
    eventDesc: "Join us for an exhilarating day where gamers of all levels come together to celebrate their passion for gaming! Test your skills in popular games such as 'Freefire' and 'BGMI'. Prizes await the top players!",
    rules: [
        "No. of Rounds : 2",
        "No modded apps are allowed.",
        "External hacks are prohibited.",
        "Any form of cheating, hacking or exploting of game bugs is prohibited.",
        "Players must adhere to game's offical rules and guidelines as specified by the develpoers.",
        "Voilating the rules will lead to disqualification.",
        "Plagarism is prohibited.",
        "Players are required to bring their own devices",
    ],
    criteria: [
        "The winning palyers will be determined by scores(eg:kills, points,etc.)",
        "Coding Proficiency.",
        "Innovation and Optimization.",
        "Adaptability and Resilence.",
    ]
},
{
    id: 7,
    img: model,
    coordinator: "Mrs. S Kayalvizhi AP/AI&DS, Mrs. V. Karthika AP/CSE, Mrs. V. Suganthi AP/CSE",
    studentCoordinator: "Mr. Sai Sabari 3rd CSE, Mr. Kumaresan 3rd AI&DS, ",
    email: "infest2k26cse@gmail.com",
    stdmobile: "6379788245",
    mobile: "8248952283",
    eventTitle: "ML - Model Training",
    eventDesc: "A simple hands-on session where participants learn how to train a machine learning model using basic data and techniques",
    rules: [
        "No. of Rounds : 1",
        "Candidates must clearly understand and define the give problem statement.before developing the model.",
        "proper data preprocessing & techinques must be followed.",
        "Appropriate ML algorithms must be selected with valid justification.",
        "Candidates must ensure orginallity in code , analyis and report",
        "2 to 3 members are allowed per team.",
        "Datasets are provided by the organizors.",

    ],
    criteria: [
        "Data preparation ",
        "Training and Optimization",
        "Evaluation & Performance",
        "Innovation & Creativity",
    ]
},
{
    id: 8,
    img: poster,
    coordinator: "Ms. T. Shampavi AP/AI&DS,Mr. Senthil Kumar AP/AI&DS,Mrs. E. Kirthika AP/CSE",
    studentCoordinator: "Mr. Manoharan 3rd IT,Mr. Krishnakumar 3rd CSE,Ms. Rinesha 3rd AI&DS",
    email: "infest2k26cse@gmail.com",
    stdmobile: "8807044820",
    mobile: "8754214893",
    eventTitle: "Poster Designing",
    eventDesc: "Join us for an exhilarating day where gamers of all levels come together to celebrate their passion for gaming! Test your skills in popular games such as 'Freefire' and 'BGMI'. Prizes await the top players!",
    rules: [
        "No. of Rounds : 1",
        "The poster must be based on the given theme/topic of the symposium. ",
        "Content should be relevant, creative, and informative. ",
        "Orientation: Will be given on spot",
        "Title, Relevant visuals/illustrations, Relevant visuals/illustrations, Short slogans or key points. ",

    ],
    criteria: [
        "Relevance to the Theme",
        "Creativity & Originality",
        "Concept & Message Clarity",
        "Layout & Organization ",
    ]
},
];
export default TechCardContent;