import {
  paperpresentation,
  projecpresentation,
  funquiz,
  pencil_sketch,
  math_puzzles,
  singing,
  mime,
} from "../../../assets/index.js";

const defaultBanner = "path/to/default/banner.jpg"; // Default banner path

const ShCardContent = [
  {
    id: 1,
    img: paperpresentation,
    banner: defaultBanner,
    coordinator: "Mrs. R.Jamunarani   AP/ S&H ",
    studentCoordinator: " Mr. K. Sittesh Ist Year CSE",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "8098997409",
    mobile: "7708203501",
    eventTitle: "Paper Presentation",
    eventDesc:
      "Participants should present their ideas within the given time. The presentation should be in the form of Microsoft Power Point. ",
    rules: [
      "Each participant will be given 7 to 10 minutes (including query session) to present their ideas within 15-20 slides.",
      "Maximum size of a team is 2 members.",
      "Participants are requested to have a copy of their presentation in their mail.",
      "All the participants are required to bring a hardcopy of their paper along with them on the day of event.",
      "The decision of judges will be final.",
      "More than one participants are allowed from one college.",
      "Kindly mail your abstract, Paper and PPT infest2k25sandh@gmail.com. Difficulties will be addressed through the same email-id.",
      "TOPICS:1.The effects of social media on human interaction",
      "TOPICS:2.Math behind GPS technology",
      "TOPICS:3.Future source of energy",
      "TOPICS:4.AI for environmental chemistry and sustainability",
    ],
    criteria: [
      "Clarity.",
      "Delivery (Confidence, Body Language, Dynamism & Vocal delivery)",
    ],
  },
  {
    id: 2,
    img: funquiz,
    banner: defaultBanner,
    coordinator: "Mrs. S.Muthulakshmi AP/ S&H Physics",
    studentCoordinator: "Ms. R. Bhavadharani Ist Year CSE",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "8883386812",
    mobile: "9659659193",
    eventTitle: "Fun Quiz",
    eventDesc:
      "A quiz, often regarded as a mental sport, is a competitive activity where participants, in teams, answer questions accurately to test their knowledge. It serves as a quick and engaging assessment tool to evaluate students' understanding, measure their progress, and enhance their abilities and skills in a fun and interactive way.",
    rules: [
      "Only team entries are eligible. ",
      "A team shall consist of two persons only.",
      "Duration - 1 hour.  ",
      "The participants shall not be allowed to use mobile or other electronic instruments. ",
      "Replacement of any participant of a team is not allowed after registration.",
      "The quiz will have 3 rounds totally. ",
      "ROUND 1: ",
      "A question will be asked to a team and if they are unable to answer it will be passed to the next team. ",
      "Each team would be asked 4 questions each. ( Objective questions with options) .",
      "10 marks for correct answer and no negative marks for the wrong answer. ",
      "If a team cannot answer the question, they can pass the question & then the question would be forwarded to the next team. ",
      "Answering time is only 35 seconds. ",
      "Team discussion is allowed. ",
      "ROUND 2:",
      "Rapid Fire Round: Each team will be asked 10 questions one after another in one minute’s time. ",
      "10 marks for the correct answer and no negative marks for the wrong answer. ",
      "Answering time is only 10 seconds. ",
      "Team discussion is allowed. ",
      "If a team cannot answer the question, they can say pass for the next question. The question will not be forwarded to the next team.",
      "ROUND 3:",
      "Each team will be asked 5 questions one after another in one minute’s time. ",
      "10 marks for the correct answer and negative 5 marks for the wrong answer.",
      "Answering time is only 30 seconds.",
    ],
    criteria: [
      "Accuracy,speed",
      "Teamwork & Participation,Bonus & Creativity",
    ],
  },

  {
    id: 3,
    img: pencil_sketch,
    banner: defaultBanner,
    coordinator: "Mrs. K. Logeshwari AP/MATHS",
    studentCoordinator: "Ms. S. Yazhini Ist Year IT",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "9363235245",
    mobile:"9489567817",
    eventTitle: "Pencil Sketch & Painting",
    eventDesc:
      "To express their ideas and emotions, with the creation of certain aesthetic qualities, in a two-dimensional visual language.",
    rules: [
      "Eligibility: Only students who have completed the registration process are eligible to participate. ",
      "Drawing Medium: Participants must use a chart as their drawing surface.",
      "Theme: The competition themes are;(i)Recycle of raw materials and reduction in plastic packaging.(ii)Climate Risk.(iii)Gender Equality clean Energy.The artwork must be done on any one of the themes.",
      "Materials: Contestants are required to bring their own drawing and painting materials, including to painting sheets, pens, pencils, brushes, watercolors, dry colors, acrylics, etc., along with a cloth for cleaning purposes.",
      "Time Limit: The allotted time for completing the artwork is 2 hours, with no extensions permitted.",
      "Color Preparation: Paint colors must be mixed and prepared at the competition venue.",
      "Clarity: The submitted artwork must have a clear and discernible image.",
      "Judging Criteria: Artworks will be evaluated based on adherence to the theme, execution quality, complexity, artistic merit, and overall presentation. The final score will be determined by averaging the judges’ evaluations.",
      "Certification: All participants will receive a certificate of participation.",
    ],
    criteria: [
      "Creativity & Originality ",
      " Technique & Skill ",
      "Composition & Presentation",
    ],
  },
  {
    id: 4,
    img: math_puzzles,
    banner: defaultBanner,
    coordinator: "Mrs. P. Sulochana Devi AP/MATHS",
    studentCoordinator: "Mr. L. Lalithsri Ist Year MECH",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "8438818350",
    mobile: "9715142264",
    eventTitle: "Math Puzzles",
    eventDesc:
      "It will be a multi-round competition where teams will tackle a variety of brain-bending math puzzles and answer rapid-fire math trivia questions. This event will also test their problem-solving skills, teamwork and mathematical prowess.",
    rules: [
      "Team Formation: Teams can have a maximum of 3 members.",
      "Rounds: The competition will consist of three rounds, each with different rules. This may include individual puzzles, collaborative challenges, and timed quizzes. ",
      "Scoring: Points will be awarded for correct answers and efficient completion of puzzles. Bonus points may be given for creative approaches and teamwork.",
      "Communication: During puzzle rounds, only one team member can communicate their solution to the judges. However, all team members can participate in discussions during quiz rounds.",
      "Equipment: Participants are permitted to bring note for rough work. However, the use of electronic devices, including smart phones, is strictly prohibited during the competition.",
      "Challenge Disputes: In case of a dispute regarding a puzzle or question, teams can present their reasoning to the judges for review. The judges' decision will be final.",
      "Adjudication: All decisions made by the event coordinators and judges are final.",
      "ROUND 1:",
      "A question will be asked to a team and if they are unable to answer it will be passed to the next team. ",
      "Each team would be asked 5 questions each. (Objective questions with options).",
      "10 marks for correct answer and no negative marks for the wrong answer. ",
      "If a team cannot answer the question, they can pass the question & then the question would be forwarded to the next team. ",
      "Answering time is only 60 seconds. ",
      "Team discussion is allowed. ",
      "ROUND 2:",
      "Each team will be asked 10 questions. ",
      "10 marks for the correct answer and no negative marks for the wrong answer. ",
      "Answering time is only 120 seconds. ",
      "Team discussion is allowed. ",
      "If a team cannot answer the question, they can say pass for the next question. The question will not be forwarded to the next team.",
      "ROUND 3:",
      "Each team will be asked 7 questions.",
      "10 marks for the correct answer.",
      "Answering time is only 120 seconds.",
    ],

    criteria: [
      "Accuracy,Speed & Time Management.",
      "Logical Thinking & Problem-Solving Approach Efficient use of logic, reasoning, and mathematical concepts.",
      "Neatness & Clarity of Work.",
    ],
  },
  {
    id: 5,
    img: singing,
    banner: defaultBanner,
    coordinator: "Mrs.V. Girija  AP / S&H ",
    studentCoordinator: "Mr. V. Durga Lakshmi Ist Year ECE ",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "8778446915",
    mobile: "9597551460",
    eventTitle: "Karaoke Singing",
    eventDesc:
      "A karaoke singing competition is an event where individuals or groups perform popular songs using pre-recorded backing tracks (karaoke) and are judged on their vocal ability, stage presence, and overall performance, competing to win prizes by showcasing their singing talent in a fun and accessible format.",
    rules: [
      "Maximum Time Limit for the song is 4-5 minutes.",
      "Songs can be in any Indian language.",
      "The judgment will be based on Shruthi, Layam, Thaalam, synchronization to the background music, time and overall performance.",
      "Your song should not have any other voice other than yours along with Karaoke.",
      "Competition is for Solo Performance only.",
      "Contestants should plan to sing at least Pallavi and Anu Pallavi. If you wish to sing Charanam, you are welcome to do so.",
      "No instruments are allowed.",
      "The decision of the Judge is final.",
    ],
    criteria: [
      "Vocal Quality & Pitch.",
      "Clarity, tone, and vocal strength.Proper control of pitch and smooth transitions between notes.",
      "Expression & Stage Presence.",
      "Confidence, charisma, and engagement with the audience.Use of facial expressions and gestures to enhance the performance.",
      "Song Selection & Difficulty.",
      "Choice of song that suits the singer’s voice and showcases skills.Extra points for tackling challenging songs.",
    ],
  },
  {
    id: 6,
    img: mime,
    banner: defaultBanner,
    coordinator: "Dr. Grace Priyadharshini AP/ S&H English",
    studentCoordinator: "Mr. M M Dinesh Kumar Ist Year CSE",
    email: "infest2k26sandh@gmail.com",
    stdmobile: "9659516157",
    mobile: "7708379796 ",
    eventTitle: "Drama or Mime",
    eventDesc:
      "Experience the power of performance in our Drama and Mime Competition! Contestants will compete in two categories: Drama, showcasing acting skills and storytelling through dialogue, and Mime, telling stories through gestures and expressions without words. This event celebrates creativity, imagination, and the art of performance, with judges looking for emotional depth, originality, and audience engagement. Don’t miss out on this captivating showcase of talent",
    rules: [
      "RULES FOR MIME:",
      "Each team can have 6-8 members.",
      "The Duration of play must not exceed 10 -12 Minutes.",
      "Negative points for exceeding the time.",
      "Music and props will be arranged by the participating team.",
      "No act shall contain any offensive, obscene, disrespectful actions or gestures. The act will be immediately stopped and the entry will be disqualified, if these instructions are not followed.",
      "Points will be given on the basis of innovation, depiction of the situation, team work and expressions.",
      "Decision of judges will be the final.",
      "RULES FOR DRAMA:",
      "Each team can have 6-8 members.",
      "The drama performance must be based on the given stimulus.",
      "No written scripts or note cards are allowed during the performance.",
      "Cell phones may not be used at any time during the performances.",
      "The Competition will be judged on the basis of the script, facial expressions, and creative use of props, stage mannerism, co-ordination, voice modulation and overall performance.",
      "Final ratings shall be decided by aggregating points awarded by a panel of judges.",
      "In case of any dispute, decision of the judges of the event shall be final and conclusive.",
    ],
    criteria: [
      "Acting Skills & Expression:Effective use of body language, facial expressions, and gestures.",
      "Creativity & Originality:Unique storyline, concept, or interpretation.Innovative and fresh approach to the theme.",
      "Dialogue Delivery & Voice Modulation (For Drama):Clear pronunciation, tone variation, and emphasis. Proper use of volume and pitch for impact.",
      "Coordination & Synchronization (For Mime):Smooth and well-coordinated movements.Clear storytelling through gestures and expressions.",
      "Stage Presence & Audience Engagement:Confidence and ability to captivate the audience.Effective use of stage space and props (if any).",
    ],
  },
];

export default ShCardContent;
