import {
    paperpresentation,
    projecpresentation,
    t_hunt,
    circuit,
    techquiz,
    t_connection
} from "../../../assets/index";

const ElectricalCardContent = [{
    id: 1,
    img: paperpresentation,
    coordinator: " Dr.A.Amutha HOD/ECE, V.Balasubramanian HOD/EEE ",
    studentCoordinator: "Nandhana.N,Manimaran.B",
    mobile: "8072834729",
    stdmobile: "9894410605",
    email: "infest2k25ece@gmail.com",
    eventTitle: "Paper Presentation",
    eventDesc: "A paper presentation is a formal way of sharing research findings, innovative ideas, or case studies with an audience in academic, professional, or technical settings. It involves presenting a well-researched paper through a structured oral talk, often supported by slides or visual aids. The goal is to communicate key insights effectively, engage the audience, and encourage discussions.  ",
    rules: [
        "Maximum 4 members per team are allowed.",
        "The paper topics can be chosen by your own.",
        "Each team is allocated a total presentation time of 10-15 minutes.",
        "Submissions must be in the form of a POWER POINT PRESENTATION (max 10 slides).",
        "Students should submit the PPT in email.",

    ],
    criteria: [
        "Problem identification and solutions to real time problems.",
        "Whether technically adoptable.",
        "Delivery (Confidence, Body Language, Dynamism).",
        ],

    },
    {
        id: 2,
        img: t_connection,
        coordinator: "Mrs.K.Gowthami, AP/ECE",
        studentCoordinator: "Gagan Kailash.R,Vijay.T,Aashika.K.S",
        mobile: "9659454522",
        stdmobile: "9345783506",
        email: "infest2k25ece@gmail.com",
        eventTitle: "Tech Connection",
        eventDesc: " The Technical Connection Event challenges participants to apply their expertise in electrical and electronics engineering through a series of interconnected tasks. Enhance participants' understanding of circuit theory and practical implementation.Develop problem-solving and teamwork skills. Encourage innovation and creativity in electrical engineering projects.Provide hands-on experience in working with electronic components and debugging techniques.",
        rules: [
            "ROUND 1:",
            "Identify the electrical and electronics components working  .",
            "Max 2 members per team .",
            "Time duration to complete 10mins .",
            "Number of question’s =10 and each questions gets 2mark.",
            "Qualification to next round above 6 marks .",
            "ROUND 2:",
            "Simulate the circuit diagram by using proteus software.",
            "Duration to complete 10mins.",
            "Qualification to next round: who simulate the output quickly they move to next round.",
            "ROUND 3:",
            "Identify the unknown resistance using voltage divider circuit .",
            "Duration to complete 10mins.",
            
        ],
        criteria: [
            "A Technical Connection Event typically involves networking, knowledge sharing, and collaboration among professionals in a specific technical field. The criteria for such an event depend on its purpose, audience, and goals.",

        ],

    },
    {
        id: 3,
        img: circuit,
        coordinator: "Mrs.P.Kowsalya, AP/ECE",
        studentCoordinator: "Poovarasi.R,Lavanya.S",
        mobile: "9626168777",
        stdmobile: "8248125472",
        email: "infest2k25ece@gmail.com",
        eventTitle: "Circuit Debugging",
        eventDesc: "Circuit Debugging is a technical event where participants, analyze and identify an analog electronic circuit. It tests their troubleshooting skills, circuit knowledge, and problem-solving abilities under time constraints.",
        rules: [
            "Two members per team.",
            "Only analog electronics type questions will be given.",
            "Winners of every round will be taken to the next round.",
            "Malpractice is not allowed.",
            "ROUND 1:",
            "Objective type question .",
            "Time duration: 15 Minutes.",
            "The top 5 teams have been selected for the next round.",
            "ROUND 2:",
            "Identify the circuits.",
            "Time duration: 60 Seconds/Question.",
            "The top 3 teams have been selected for the next round.",
            "ROUND 3:",
            "Draw the circuit for given title.",
            "Time duration: 10 Minutes.",
            "The 1 team has been selected as winner.",
            "Usage of Mobile is Restricted.",
            "Certificates will be provided for all the participants and winners.",
        ],
        criteria: [
            "Circuit Debugging Event, the criteria should focus on testing participants’ ability to troubleshoot, analyze, and fix circuit-related issues efficiently. ",
            "Engineering students (electronics, electrical, mechatronics, etc.).Professionals in embedded systems, PCB design, or electrical engineering.",
            "Basic Component Faults,Power Supply Issues,Signal Integrity Problems,Incorrect Circuit Design,Microcontroller & Embedded Debugging,PCB Debugging.",
            "Required Tools & Resources,Participation Rules & Guidelines.",
        ],
    },
    {
        id: 4,
        img: t_hunt,
        coordinator: "Mr.B.Kaviraj, AP/EEE",
        studentCoordinator: "Hariharapandian.S,Valanprakash.R,",
        mobile: "9629099432",
        stdmobile: "8610501700",
        email: "infest2k25ece@gmail.com",
        eventTitle: "Treasure Hunt",
        eventDesc: "The Treasure Hunt Round is an exciting and intellectually stimulating challenge designed to test participants' technical knowledge, problem-solving skills, and teamwork in a fun and engaging way. Participants must follow a trail of clues, solve puzzles, and complete tasks to reach the final treasure. ",
        rules: [
            "ROUND 1:",
            "Find the electric Treasure  .",
            "Max 3 members per team .",
            "Time duration to complete 10mins .",
            "ROUND 2:",
            "Scan the QR and identify the treasure   .",
            "Duration to complete 15mins .",
            "Qualified teams move to next round .",
            "The final round will be played between top three teams who successfully passed round 2. ",
            "Duration to complete 5 mins .",
            "GENERAL RULES:",
            "Teamwork: Teams must work together, staying within sight and earshot of each other. ",
            "Clue Order: Clues must be found and solved in the correct order, and skipping a clue leads to disqualification. ",
            "No Cheating: No using phones or other devices to communicate or get help with clues unless separated.",
            "Safety First: Participants should be aware of their surroundings and take necessary precautions for safety.  ",
            "Respect the Environment: Participants should not damage property or litter. ",
        ],
        criteria: [
            "A Treasure Hunt Event is an engaging and interactive game where participants solve clues and complete challenges to find a hidden treasure or reach a final destination.",

        ],

    },
    {
        id: 5,
        img: projecpresentation,
        coordinator: "Ms.S.Sowmiya,AP/EEE",
        studentCoordinator: "Gagan Kailash.R",
        mobile: "9443516740",
        stdmobile: "7871896070",
        email: "infest2k25ece@gmail.com",
        eventTitle: "Project Presentation",
        eventDesc: "Project Expo showcases student innovations through two rounds: online prelims and offline finals.Participants present projects, engage with experts, and compete for certificates and prizes. ",
        rules: [
            "ONLINE PRELIMS:",
            "Upload the Wordfile in the google drive.",
            "Register online and submit a Project PPT (problem statement, working mechanism, innovation). ",
            "1-minute video (Demonstration) is optional but encouraged.",
            "OFFLINE ROUNDS:",
            "Per team only 2-4 members.",
            "Shortlisted participants present a 10-minute demo followed by a 5-minute QA with judges.",
            "GUIDELINES:",
            "Meet registration and submission deadlines. ",
            "Projects must be functional for the offline round .",
            "Non-attendance leads to disqualification. ",
        ],
        criteria: [
            "A Project Presentation Event evaluates participants' ability to showcase their work effectively, covering innovation, technical depth, presentation skills, and impact. ",
        ],
    },
    {
        id: 6,
        img: techquiz,
        coordinator: "Mrs. B.Bharathi, AP/ECE",
        studentCoordinator: "jothimani.G IInd Year EEE , Sujeesh.M IInd Yaer EEE,",
        mobile: "9500740800",
        stdmobile: "8248082415",
        email: "infest2k25ece@gmail.com",
        eventTitle: "Techical Quiz",
        eventDesc: "Tech Brains is a challenging and engaging technical quiz competition designed to test participants' knowledge in various engineering domains. This event aims to foster a competitive spirit while enhancing problem-solving skills, technical awareness, and innovative thinking. ",
        rules: [
            "ROUND 1:",
            "General quiz   .",
            "Max 2 members per team .",
            "Time duration to complete 10 mins .",
            "Number of question’s = 20 and each questions gets 2mark.",
            "Qualification to next round above 16 marks .",
            "ROUND 2:",
            "Identify the electrical and electronics devices images.",
            "Duration to complete 10mins .",
            "Number of question’s =10 and each questions gets 2mark.",
            "Qualification to next round above 12 marks .",
            "ROUND 3:",
            "Tech quiz   .",
            "Duration to complete 10mins .",
            "Number of question’s =15 and each questions gets 2mark .",
            "NOTE:Mobile Phone Is Prohibited  and Unwanted Discussion or Helping Other Friends You Will Disqualify.",


        ],
        criteria: [
            "A Technical Quiz Event is a knowledge-based competition that tests participants on various technical subjects such as engineering, IT, science, and technology. ",

        ],
    },
];

export default ElectricalCardContent;