import {
    paperpresentation,
    projecpresentation,
    t_hunt,
    circuit,
    techquiz,
    t_connection,
    design,
} from "../../../assets/index";

const ElectricalCardContent = [{
    id: 1,
    img: paperpresentation,
    coordinator: " Dr.A.Amutha HOD/ECE, V.Balasubramanian HOD/EEE ",
    studentCoordinator: "Arunkumar .N,Manimaran.B",
    mobile: "802834729",
    stdmobile: "8015017758",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Paper Presentation",
    venue: "Info Institute of Engineering",
    eventDesc: "A paper presentation is a formal way of sharing research findings, innovative ideas, or case studies with an audience in academic, professional, or technical settings. It involves presenting a well-researched paper through a structured oral talk, often supported by slides or visual aids. The goal is to communicate key insights effectively, engage the audience, and encourage discussions.  ",
    rules: [
        "Maximum 4 members per team are allowed.",
        "The paper topics can be chosen by your own.",
        "Each team is allocated a total presentation time of 10-15 minutes.",
        "Submissions must be in the form of a POWER POINT PRESENTATION (max 10 slides).",
        "Students should submit the PPT in email.(infest2k26ece@gmail.com)",

    ],
    criteria: [
        "Problem identification and solutions to real time problems.",
        "Whether technically adoptable.",
        "Delivery (Confidence, Body Language, Dynamism).",
    ],

},
{
    id: 2,
    img: t_connection,
    coordinator: "Mrs. K. Gowthami AP/ECE , Mrs. D. Joy marlin AP/EEE",
    studentCoordinator: "Vijay.T,Saruthi R",
    mobile: "9659454522",
    stdmobile: "9345783506",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Tech Connection",
    venue: "Info Institute of Engineering",
    eventDesc: " The Technical Connection Event challenges participants to apply their expertise in electrical and electronics engineering through a series of interconnected tasks. Enhance participants' understanding of circuit theory and practical implementation.Develop problem-solving and teamwork skills. Encourage innovation and creativity in electrical engineering projects.Provide hands-on experience in working with electronic components and debugging techniques.",
    rules: [
        "ROUND 1:",
        "Identify the electrical and electronics components working  .",
        "Max 2 members per team .",
        "Time duration to complete 10mins .",
        "Number of question’s =10 and each questions gets 2mark.",
        "Qualification to next round above 6 marks .",
        "ROUND 2:",
        "Simulate the circuit diagram by using proteus software.",
        "Duration to complete 10mins.",
        "Qualification to next round: who simulate the output quickly they move to next round.",
        "ROUND 3:",
        "Identify the unknown resistance using voltage divider circuit .",
        "Duration to complete 10mins.",

    ],
    criteria: [
        "A Technical Connection Event typically involves networking, knowledge sharing, and collaboration among professionals in a specific technical field. The criteria for such an event depend on its purpose, audience, and goals.",

    ],

},
{
    id: 3,
    img: circuit,
    coordinator: "Mrs.P.Kowsalya AP/ECE, Mrs. K. Bhuvana AP/EEE",
    studentCoordinator: "Dharshini.R,Naveen kumar",
    mobile: "9626168777",
    stdmobile: "9360385377",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Circuit Debugging",
    venue: "Info Institute of Engineering",
    eventDesc: "Circuit Debugging is a technical event where participants, analyze and identify an analog electronic circuit. It tests their troubleshooting skills, circuit knowledge, and problem-solving abilities under time constraints.",
    rules: [
        "Two members per team.",
        "Only analog electronics type questions will be given.",
        "Winners of every round will be taken to the next round.",
        "Malpractice is not allowed.",
        "ROUND 1:",
        "Objective type question .",
        "Time duration: 15 Minutes.",
        "The top 5 teams have been selected for the next round.",
        "ROUND 2:",
        "Identify the circuits.",
        "Time duration: 60 Seconds/Question.",
        "The top 3 teams have been selected for the next round.",
        "ROUND 3:",
        "Draw the circuit for given title.",
        "Time duration: 10 Minutes.",
        "The 1 team has been selected as winner.",
        "Usage of Mobile is Restricted.",
        "Certificates will be provided for all the participants and winners.",
    ],
    criteria: [
        "Circuit Debugging Event, the criteria should focus on testing participants’ ability to troubleshoot, analyze, and fix circuit-related issues efficiently. ",
        "Engineering students (electronics, electrical, mechatronics, etc.).Professionals in embedded systems, PCB design, or electrical engineering.",
        "Basic Component Faults,Power Supply Issues,Signal Integrity Problems,Incorrect Circuit Design,Microcontroller & Embedded Debugging,PCB Debugging.",
        "Required Tools & Resources,Participation Rules & Guidelines.",
    ],
},
{
    id: 4,
    img: design,
    coordinator: "Mrs.B.Bharathi  AP/ECE,Mrs. C. Tamilselvi AP/EEE ",
    studentCoordinator: "Arun kumar .S,Arivu .A,",
    mobile: "9500740800",
    stdmobile: "9994956296",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Circuit Designing",
    venue: "Info Institute of Engineering",
    eventDesc: " Apaper-basedtechnical event where participants design, analyze, and modify electronic circuits within a fixed time, testing their fundamental knowledge and problem-solving skills.",
    rules: [
        "ROUND 1 : Circuit Design Round",
        "Participants must design a circuit based on the given problem statement..",
        "Proper labeling of all components and connections is mandatory.",
        "Time Duration to complete 10 mins",
        "No. of questions = 10.Eachquestion gets 2 marks.",
        "Qualification to the next round above 12 marks.",
        "ROUND 2 : Circuit Analysis & Component Identification Round",
        "Participants will be provided with a circuit diagram that has some missing components.",
        "The task is to identify the missing components correctly.",
        "Participants must place the identified components in the correct positions on the answer sheet provided.",
        "Proper component symbols and values (if required) must be mentioned.",
        "Time duration to complete 10 mins.",
        "GENERAL RULES:",
        "Mobile Phone Is Prohibited.",
        "Unwanted Discussion or Helping Other Friends You Will Disqualify. ",
    ],
    criteria: [
        "Technical Accuracy",
        "Clarity & Presentation",
        "Problem-Solving & Logical Thinking",
        "Time Management &  Efficiency",
        "Rule Adherence & Professional Conduct",

    ],

},
{
    id: 5,
    img: projecpresentation,
    coordinator: "Ms.R.K. Madhu shre AP/ECE,Mrs.s.Sowmiya  AP/EEE",
    studentCoordinator: "Karthikeyan .S, Praveen ",
    mobile: "8754057796",
    stdmobile: "8870421077",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Project Presentation",
    venue: "Info Institute of Engineering",
    eventDesc: "Project Expo showcases student innovations through two rounds: online prelims and offline finals.Participants present projects, engage with experts, and compete for certificates and prizes. ",
    rules: [
        "ONLINE PRELIMS:",
        "Upload the Wordfile in the google drive.",
        "Register online and submit a Project PPT (problem statement, working mechanism, innovation). ",
        "1-minute video (Demonstration) is optional but encouraged.",
        "OFFLINE ROUNDS:",
        "Per team only 2-4 members.",
        "Shortlisted participants present a 10-minute demo followed by a 5-minute QA with judges.",
        "GUIDELINES:",
        "Meet registration and submission deadlines. ",
        "Projects must be functional for the offline round .",
        "Non-attendance leads to disqualification. ",
    ],
    criteria: [
        "A Project Presentation Event evaluates participants' ability to showcase their work effectively, covering innovation, technical depth, presentation skills, and impact. ",
    ],
},
{
    id: 6,
    img: techquiz,
    coordinator: "Mrs. P.Gunaranjani AP/ECE,Mr.B.Kaviraj AP/EEE",
    studentCoordinator: "S.Lavanya , Sujeesh.M ",
    mobile: "9629099432",
    stdmobile: "8870380537",
    email: "infest2k26ece@gmail.com",
    eventTitle: "Techical Quiz",
    venue: "Info Institute of Engineering",
    eventDesc: "Tech Brains is a challenging and engaging technical quiz competition designed to test participants' knowledge in various engineering domains. This event aims to foster a competitive spirit while enhancing problem-solving skills, technical awareness, and innovative thinking. ",
    rules: [
        "ROUND 1:",
        "General quiz   .",
        "Max 2 members per team .",
        "Time duration to complete 10 mins .",
        "Number of question’s = 20 and each questions gets 2mark.",
        "Qualification to next round above 16 marks .",
        "ROUND 2:",
        "Identify the electrical and electronics devices images.",
        "Duration to complete 10mins .",
        "Number of question’s =10 and each questions gets 2mark.",
        "Qualification to next round above 12 marks .",
        "ROUND 3:",
        "Tech quiz   .",
        "Duration to complete 10mins .",
        "Number of question’s =15 and each questions gets 2mark .",
        "NOTE:Unwanted Discussion or Helping Other Friends You Will Disqualify.",


    ],
    criteria: [
        "A Technical Quiz Event is a knowledge-based competition that tests participants on various technical subjects such as engineering, IT, science, and technology. ",

    ],
},
];

export default ElectricalCardContent;